### ISSUE TITLE
App.py file is missing 

### ISSUE THREAD

**Issue by suki1504** [skandermenzli/ANPR_Yolov8#1]
Hi @skandermenzli 

can you please share app.py it will very usefull for my studies 

thanks

**Comment by skandermenzli** [comment]
Hi,

That was a mistake in the readme u should run the main file

I updated the readme u can check the command

Thank you for pointing this out

________________________________
From: susmitha ***@***.***>
Sent: Thursday, September 14, 2023 2:44 PM
To: skandermenzli/ANPR_Yolov8 ***@***.***>
Cc: skandermenzli ***@***.***>; Mention ***@***.***>
Subject: [skandermenzli/ANPR_Yolov8] App.py file is missing (Issue #1)


Hi @skandermenzli<https://github.com/skandermenzli>

can you please share app.py it will very usefull for my studies

thanks
